### ISSUE TITLE
خطای  امضا

### ISSUE THREAD

**Issue by amir3164** [Torabi-srh/Moadian#5]
سلام خطای زیر دلیلش  چیه. کلید خصوصی و عمومی رو درست وارد میکنم
{"signature":null,"signatureKeyId":null,"timestamp":1687234272536,"errors":[{"detail":"امضای بسته صحیح نمی باشد","errorCode":"4011"}]}

**Comment by Bahrami1368** [comment]
منم همین مشکل رو خوردم اگر امکانش هست راهنمایی بفرمایید

**Comment by amir3164** [comment]
سلام این  مقادیر رو بدین درست میشه. 
```
public async Task<TokenModel> GetToken(

          packet.fiscalId = "";
            packet.uid = "";
            packet.encryptionKeyId = "";
            packet.symmetricKey = "";
            packet.iv = "";
            packet.dataSignature = "";
```
